export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/categories/pizzaIcon.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/categories/burger.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/categories/italian.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/categories/pizzaIcon.png"),
  },

  {
    id: 5,
    name: "Sweets",
    image: require("../assets/categories/sweets.png"),
  },
];

export const featured = {
  id: 1,
  title: "Featured",
  description: "Find the best options this week",
  restaurants: [
    {
      id: 1,
      name: "Pice Pizza",
      image: require("../assets/restaurants/restaurantImg.jpg"),
      description: "Hot and Spicy Pizza",
      lat: 5.6037,
      lng: -0.187,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 175,
          image: require("../assets/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Fried Chicken",
          description: "spicy fried chicken",
          price: 60,
          image: require("../assets/dishes/chicken.jpeg"),
        },
        {
          id: 3,
          name: "Hamburger",
          description: "Burger filled with ham",
          price: 40,
          image: require("../assets/dishes/burger.jpeg"),
        },
      ],
    },
    {
      id: 2,
      name: "KFC",
      image: require("../assets/restaurants/restaurant1.webp"),
      description: "Hot and Spicy Pizza",
      lat: 5.6037,
      lng: -0.187,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 175,
          image: require("../assets/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Fried Chicken",
          description: "spicy fried chicken",
          price: 60,
          image: require("../assets/dishes/chicken.jpeg"),
        },
        {
          id: 3,
          name: "Hamburger",
          description: "Burger filled with ham",
          price: 40,
          image: require("../assets/dishes/burger.jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "Aduanepa",
      image: require("../assets/restaurants/aduanepa.jpg"),
      description: "Hot and Spicy Pizza",
      lat: 5.6037,
      lng: -0.187,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 175,
          image: require("../assets/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Fried Chicken",
          description: "spicy fried chicken",
          price: 60,
          image: require("../assets/dishes/chicken.jpeg"),
        },
        {
          id: 3,
          name: "Hamburger",
          description: "Burger filled with ham",
          price: 40,
          image: require("../assets/dishes/burger.jpeg"),
        },
      ],
    },
  ],
};
